### PR TITLE
Support querying total number of bits read/written

### PR DESCRIPTION
**Pull request by Danaozhong**
This will enhance the bitio reader/writer by a function to query the total number of bits read/written.
This is useful is users want to put/parse data in fixed offsets from each other.

### CODE REVIEW

**Comment by icza** [comment]
Thanks for the PR.

While this is a nice addition, it is rarely needed. And I think the performance penalty for those who don't need it is not acceptable. This library ought to be fast.

I propose the counting to be optional. Rather than building it into `Reader` and `Writer`, I suggest to create separate implementations `CountReader` and `CountWriter` which may use the existing `Reader` and `Writer` implementations, and maintain the bits count additionally.

This way if someone doesn't need the counts may continue to use `Reader` and `Writer`, and those who do need it may use `CountReader` and `CountWriter`. A win-win situation.

Thoughts? Do you want to create the `CountReader` and `CountWriter` or should I?

**Comment by Danaozhong** [comment]
Sounds fine with me. I have refactored the changes into `CountReader` and `CountWriter`. Let me know if this current implementation works for you, then I can do some prettifying.

**Comment by icza** [comment]
At a quick glance I like it.

Things I would change:

- I would embed `*Reader` in `CountReader` though, and similarly `*Writer` in `CountWriter`. Any reason why you embed non-pointers?
- I would use `int64` for the `bitPosition` fields instead of `uint64`, it's easier to work with signed types, don't have to worry about overflow (those that query and use the read / written bits). The implementation gets simpler too (no `uint64` conversions). If you think about it: `io.Reader.Read()` and `io.Writer.Write()` also return signed counts.

**Comment by icza** [comment]
It looks good now. Thanks again for the PR.

**Comment by icza** [comment]
I've made a few changes, most notably exporting the field and using the consistent name `BitsCount` both in `CountReader` and `CountWriter`. Also created a new v1.1.0 version. Thanks again.

**Comment by Danaozhong** [comment]
Thank you very much, I am happy this feature is now available!

**Pull request merged**
